server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        # 🔥 AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # 🔥 EMPLOYEE SERVICE
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**

        # 🔥 PROJECT SERVICE
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**

        # 🔥 CLIENT SERVICE
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**

        # 🔥 DASHBOARD SERVICE
        - id: dashboard-service
          uri: lb://DASHBOARD-SERVICE
          predicates:
            - Path=/dashboard/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    enabled: true

eureka:
  client:
    # 🔥 FIX: localhost CI/Docker me work nahi karega
    # service-name use hota hai
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

    register-with-eureka: true
    fetch-registry: true