server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER

logging:
  level:
    com.netflix.eureka: ERROR
    com.netflix.discovery: ERROR
    org.springframework.cloud.netflix.eureka: ERROR

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false